// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3RYUXa0Iiuh_8wVfCB4v03zbIdtrypIo',
    appId: '1:874589113625:web:79d5f88cb12abcf3664988',
    messagingSenderId: '874589113625',
    projectId: 'vishwanath-app',
    authDomain: 'vishwanath-app.firebaseapp.com',
    storageBucket: 'vishwanath-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoSPvzd8ea7rYUbQIXr56Mnuz3uU9atmE',
    appId: '1:874589113625:android:d487700d038fa7bb664988',
    messagingSenderId: '874589113625',
    projectId: 'vishwanath-app',
    storageBucket: 'vishwanath-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj4d-UIt5z80We4_RmqDlkBWpevym18gw',
    appId: '1:874589113625:ios:e61ee34f947b8111664988',
    messagingSenderId: '874589113625',
    projectId: 'vishwanath-app',
    storageBucket: 'vishwanath-app.firebasestorage.app',
    iosBundleId: 'com.example.vishwanathApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj4d-UIt5z80We4_RmqDlkBWpevym18gw',
    appId: '1:874589113625:ios:e61ee34f947b8111664988',
    messagingSenderId: '874589113625',
    projectId: 'vishwanath-app',
    storageBucket: 'vishwanath-app.firebasestorage.app',
    iosBundleId: 'com.example.vishwanathApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3RYUXa0Iiuh_8wVfCB4v03zbIdtrypIo',
    appId: '1:874589113625:web:8fe1ddcb1c19f5fa664988',
    messagingSenderId: '874589113625',
    projectId: 'vishwanath-app',
    authDomain: 'vishwanath-app.firebaseapp.com',
    storageBucket: 'vishwanath-app.firebasestorage.app',
  );
}
